import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

/**
 * Predefined popular ETF data with well-known metrics.
 * Used to seed the database if no ETF profiles exist.
 */
const POPULAR_ETFS = [
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.09,
    trackingIndex: 'S&P 500',
    aum: 530000,
    dividendYield: 1.4,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 1.0,
    sharpe1y: 1.85,
    volatility1y: 12.5,
    returns1y: 24.5,
    returns3y: 10.2,
    returns5y: 15.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', weight: 3.3 },
      { symbol: 'GOOG', name: 'Alphabet Inc. Class C', weight: 3.1 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 2.1 },
      { symbol: 'LLY', name: 'Eli Lilly and Co.', weight: 1.8 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 1.7 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Industrials', weight: 8.2 },
      { sector: 'Consumer Staples', weight: 5.8 },
      { sector: 'Energy', weight: 3.8 },
      { sector: 'Utilities', weight: 2.5 },
      { sector: 'Real Estate', weight: 2.3 },
      { sector: 'Materials', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.5 },
      { region: 'Other', weight: 1.5 },
    ]),
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.20,
    trackingIndex: 'NASDAQ-100',
    aum: 260000,
    dividendYield: 0.6,
    peRatio: 32.1,
    pbRatio: 7.2,
    beta: 1.15,
    sharpe1y: 2.1,
    volatility1y: 18.2,
    returns1y: 28.3,
    returns3y: 12.5,
    returns5y: 19.1,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 8.5 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 8.2 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 7.5 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 5.2 },
      { symbol: 'META', name: 'Meta Platforms', weight: 4.8 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', weight: 4.5 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 3.2 },
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 3.0 },
      { symbol: 'COST', name: 'Costco Wholesale', weight: 2.5 },
      { symbol: 'NFLX', name: 'Netflix Inc.', weight: 2.1 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 52.8 },
      { sector: 'Communication Services', weight: 16.2 },
      { sector: 'Consumer Discretionary', weight: 13.5 },
      { sector: 'Healthcare', weight: 7.5 },
      { sector: 'Industrials', weight: 5.2 },
      { sector: 'Consumer Staples', weight: 3.5 },
      { sector: 'Other', weight: 1.3 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 97.0 },
      { region: 'Other', weight: 3.0 },
    ]),
  },
  {
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.03,
    trackingIndex: 'CRSP US Total Market',
    aum: 340000,
    dividendYield: 1.3,
    peRatio: 24.0,
    pbRatio: 4.5,
    beta: 1.0,
    sharpe1y: 1.8,
    volatility1y: 13.0,
    returns1y: 23.0,
    returns3y: 9.5,
    returns5y: 14.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 6.2 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 5.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 4.5 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.2 },
      { symbol: 'META', name: 'Meta Platforms', weight: 2.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 28.5 },
      { sector: 'Healthcare', weight: 12.5 },
      { sector: 'Financials', weight: 12.0 },
      { sector: 'Consumer Discretionary', weight: 10.5 },
      { sector: 'Industrials', weight: 9.0 },
      { sector: 'Communication Services', weight: 7.5 },
      { sector: 'Consumer Staples', weight: 5.5 },
      { sector: 'Energy', weight: 4.0 },
      { sector: 'Utilities', weight: 2.8 },
      { sector: 'Real Estate', weight: 3.2 },
      { sector: 'Materials', weight: 2.5 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 99.0 },
      { region: 'Other', weight: 1.0 },
    ]),
  },
  {
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.03,
    trackingIndex: 'S&P 500',
    aum: 440000,
    dividendYield: 1.35,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 1.0,
    sharpe1y: 1.85,
    volatility1y: 12.5,
    returns1y: 24.5,
    returns3y: 10.2,
    returns5y: 15.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Industrials', weight: 8.2 },
      { sector: 'Consumer Staples', weight: 5.8 },
      { sector: 'Energy', weight: 3.8 },
      { sector: 'Utilities', weight: 2.5 },
      { sector: 'Real Estate', weight: 2.3 },
      { sector: 'Materials', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.5 },
      { region: 'Other', weight: 1.5 },
    ]),
  },
  {
    symbol: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.03,
    trackingIndex: 'S&P 500',
    aum: 420000,
    dividendYield: 1.35,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 1.0,
    sharpe1y: 1.85,
    volatility1y: 12.5,
    returns1y: 24.5,
    returns3y: 10.2,
    returns5y: 15.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Industrials', weight: 8.2 },
      { sector: 'Consumer Staples', weight: 5.8 },
      { sector: 'Energy', weight: 3.8 },
      { sector: 'Utilities', weight: 2.5 },
      { sector: 'Real Estate', weight: 2.3 },
      { sector: 'Materials', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.5 },
      { region: 'Other', weight: 1.5 },
    ]),
  },
  {
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.19,
    trackingIndex: 'Russell 2000',
    aum: 64000,
    dividendYield: 1.2,
    peRatio: 18.5,
    pbRatio: 2.2,
    beta: 1.15,
    sharpe1y: 1.1,
    volatility1y: 19.5,
    returns1y: 15.0,
    returns3y: 3.5,
    returns5y: 8.2,
    topHoldings: JSON.stringify([
      { symbol: 'SMCI', name: 'Super Micro Computer', weight: 1.2 },
      { symbol: 'MSTR', name: 'MicroStrategy Inc.', weight: 1.0 },
      { symbol: 'INSM', name: 'Insmed Inc.', weight: 0.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Healthcare', weight: 18.5 },
      { sector: 'Industrials', weight: 17.0 },
      { sector: 'Financials', weight: 15.5 },
      { sector: 'Technology', weight: 14.2 },
      { sector: 'Consumer Discretionary', weight: 11.8 },
      { sector: 'Consumer Staples', weight: 5.5 },
      { sector: 'Real Estate', weight: 7.5 },
      { sector: 'Energy', weight: 4.8 },
      { sector: 'Materials', weight: 3.5 },
      { sector: 'Utilities', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 99.5 },
      { region: 'Other', weight: 0.5 },
    ]),
  },
  {
    symbol: 'EFA',
    name: 'iShares MSCI EAFE ETF',
    market: 'US',
    category: 'international',
    expenseRatio: 0.32,
    trackingIndex: 'MSCI EAFE',
    aum: 53000,
    dividendYield: 3.1,
    peRatio: 15.8,
    pbRatio: 1.8,
    beta: 0.85,
    sharpe1y: 1.2,
    volatility1y: 12.0,
    returns1y: 14.2,
    returns3y: 5.8,
    returns5y: 8.5,
    topHoldings: JSON.stringify([
      { symbol: 'NVO', name: 'Novo Nordisk', weight: 1.8 },
      { symbol: 'ASML', name: 'ASML Holding', weight: 1.5 },
      { symbol: 'SAP', name: 'SAP SE', weight: 1.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Financials', weight: 18.5 },
      { sector: 'Consumer Staples', weight: 12.0 },
      { sector: 'Healthcare', weight: 11.5 },
      { sector: 'Industrials', weight: 11.0 },
      { sector: 'Technology', weight: 10.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 7.5 },
      { sector: 'Materials', weight: 6.8 },
      { sector: 'Energy', weight: 5.2 },
      { sector: 'Utilities', weight: 3.8 },
      { sector: 'Real Estate', weight: 3.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'Japan', weight: 22.5 },
      { region: 'United Kingdom', weight: 15.2 },
      { region: 'France', weight: 10.8 },
      { region: 'Germany', weight: 8.5 },
      { region: 'Switzerland', weight: 8.2 },
      { region: 'Australia', weight: 6.8 },
      { region: 'Other', weight: 28.0 },
    ]),
  },
  {
    symbol: 'AGG',
    name: 'iShares Core US Aggregate Bond ETF',
    market: 'US',
    category: 'bond',
    expenseRatio: 0.03,
    trackingIndex: 'Bloomberg US Aggregate Bond',
    aum: 115000,
    dividendYield: 4.2,
    peRatio: null,
    pbRatio: null,
    beta: 0.05,
    sharpe1y: 0.5,
    volatility1y: 5.5,
    returns1y: 2.5,
    returns3y: -2.5,
    returns5y: 0.5,
    topHoldings: JSON.stringify([
      { symbol: 'US10Y', name: 'US Treasury 10Y', weight: 8.5 },
      { symbol: 'US5Y', name: 'US Treasury 5Y', weight: 6.2 },
      { symbol: 'US30Y', name: 'US Treasury 30Y', weight: 5.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Government', weight: 42.5 },
      { sector: 'Corporate (Investment Grade)', weight: 28.2 },
      { sector: 'Mortgage-Backed', weight: 25.0 },
      { sector: 'Other', weight: 4.3 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
  {
    symbol: 'BND',
    name: 'Vanguard Total Bond Market ETF',
    market: 'US',
    category: 'bond',
    expenseRatio: 0.03,
    trackingIndex: 'Bloomberg US Total Bond',
    aum: 100000,
    dividendYield: 4.1,
    peRatio: null,
    pbRatio: null,
    beta: 0.05,
    sharpe1y: 0.45,
    volatility1y: 5.8,
    returns1y: 2.2,
    returns3y: -2.8,
    returns5y: 0.3,
    topHoldings: JSON.stringify([
      { symbol: 'US10Y', name: 'US Treasury 10Y', weight: 9.0 },
      { symbol: 'US5Y', name: 'US Treasury 5Y', weight: 7.5 },
      { symbol: 'US30Y', name: 'US Treasury 30Y', weight: 5.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Government', weight: 45.0 },
      { sector: 'Corporate (Investment Grade)', weight: 25.5 },
      { sector: 'Mortgage-Backed', weight: 24.5 },
      { sector: 'Other', weight: 5.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
  {
    symbol: 'VWO',
    name: 'Vanguard Emerging Markets ETF',
    market: 'US',
    category: 'international',
    expenseRatio: 0.08,
    trackingIndex: 'FTSE Emerging Markets',
    aum: 78000,
    dividendYield: 2.8,
    peRatio: 14.2,
    pbRatio: 1.5,
    beta: 0.95,
    sharpe1y: 0.8,
    volatility1y: 15.5,
    returns1y: 10.5,
    returns3y: -2.5,
    returns5y: 3.2,
    topHoldings: JSON.stringify([
      { symbol: 'TSM', name: 'Taiwan Semiconductor', weight: 8.5 },
      { symbol: '600519.SS', name: 'Kweichow Moutai', weight: 2.2 },
      { symbol: 'PDD', name: 'PDD Holdings', weight: 1.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 22.5 },
      { sector: 'Financials', weight: 20.8 },
      { sector: 'Consumer Discretionary', weight: 12.5 },
      { sector: 'Communication Services', weight: 10.2 },
      { sector: 'Consumer Staples', weight: 7.5 },
      { sector: 'Materials', weight: 6.8 },
      { sector: 'Energy', weight: 5.5 },
      { sector: 'Industrials', weight: 5.0 },
      { sector: 'Healthcare', weight: 4.2 },
      { sector: 'Utilities', weight: 3.0 },
      { sector: 'Real Estate', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'China', weight: 32.5 },
      { region: 'Taiwan', weight: 18.2 },
      { region: 'India', weight: 14.5 },
      { region: 'Brazil', weight: 5.8 },
      { region: 'Saudi Arabia', weight: 4.2 },
      { region: 'South Africa', weight: 3.5 },
      { region: 'Other', weight: 21.3 },
    ]),
  },
  {
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    market: 'US',
    category: 'commodity',
    expenseRatio: 0.40,
    trackingIndex: 'Gold Price',
    aum: 72000,
    dividendYield: 0,
    peRatio: null,
    pbRatio: null,
    beta: -0.05,
    sharpe1y: 1.5,
    volatility1y: 13.0,
    returns1y: 20.0,
    returns3y: 8.5,
    returns5y: 10.5,
    topHoldings: JSON.stringify([
      { symbol: 'GOLD', name: 'Gold Bullion', weight: 99.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Commodities', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'Global', weight: 100.0 },
    ]),
  },
  {
    symbol: 'SLV',
    name: 'iShares Silver Trust',
    market: 'US',
    category: 'commodity',
    expenseRatio: 0.50,
    trackingIndex: 'Silver Price',
    aum: 15000,
    dividendYield: 0,
    peRatio: null,
    pbRatio: null,
    beta: 0.1,
    sharpe1y: 0.9,
    volatility1y: 22.0,
    returns1y: 18.0,
    returns3y: 5.2,
    returns5y: 7.8,
    topHoldings: JSON.stringify([
      { symbol: 'SILVER', name: 'Silver Bullion', weight: 99.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Commodities', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'Global', weight: 100.0 },
    ]),
  },
  {
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Financials Select Sector',
    aum: 42000,
    dividendYield: 1.6,
    peRatio: 14.5,
    pbRatio: 1.6,
    beta: 1.05,
    sharpe1y: 1.6,
    volatility1y: 15.0,
    returns1y: 18.5,
    returns3y: 8.2,
    returns5y: 10.5,
    topHoldings: JSON.stringify([
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 13.2 },
      { symbol: 'JPM', name: 'JPMorgan Chase', weight: 9.8 },
      { symbol: 'V', name: 'Visa Inc.', weight: 8.5 },
      { symbol: 'MA', name: 'Mastercard Inc.', weight: 7.2 },
      { symbol: 'BAC', name: 'Bank of America', weight: 5.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Banks', weight: 35.0 },
      { sector: 'Insurance', weight: 15.0 },
      { sector: 'Capital Markets', weight: 18.0 },
      { sector: 'Payment Processing', weight: 20.0 },
      { sector: 'Other Financials', weight: 12.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
  {
    symbol: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Technology Select Sector',
    aum: 56000,
    dividendYield: 0.7,
    peRatio: 35.5,
    pbRatio: 8.5,
    beta: 1.2,
    sharpe1y: 2.2,
    volatility1y: 18.5,
    returns1y: 30.0,
    returns3y: 14.5,
    returns5y: 22.0,
    topHoldings: JSON.stringify([
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 21.5 },
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 20.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 12.5 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 5.2 },
      { symbol: 'CRM', name: 'Salesforce Inc.', weight: 3.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Software', weight: 35.0 },
      { sector: 'Semiconductors', weight: 25.0 },
      { sector: 'Hardware', weight: 18.0 },
      { sector: 'IT Services', weight: 12.0 },
      { sector: 'Other Technology', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.0 },
      { region: 'Other', weight: 2.0 },
    ]),
  },
  {
    symbol: 'VGT',
    name: 'Vanguard Information Technology ETF',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.10,
    trackingIndex: 'MSCI US Investable Market Info Tech 25/50',
    aum: 65000,
    dividendYield: 0.8,
    peRatio: 34.2,
    pbRatio: 9.0,
    beta: 1.18,
    sharpe1y: 2.15,
    volatility1y: 17.8,
    returns1y: 28.5,
    returns3y: 13.8,
    returns5y: 20.5,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 18.5 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 16.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 8.5 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 4.2 },
      { symbol: 'CRM', name: 'Salesforce Inc.', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Software', weight: 38.0 },
      { sector: 'Semiconductors', weight: 22.0 },
      { sector: 'Hardware', weight: 15.0 },
      { sector: 'IT Services', weight: 14.0 },
      { sector: 'Other Technology', weight: 11.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 97.5 },
      { region: 'Other', weight: 2.5 },
    ]),
  },
  {
    symbol: 'IBB',
    name: 'iShares Biotechnology ETF',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.45,
    trackingIndex: 'ICE Biotechnology',
    aum: 8500,
    dividendYield: 0.3,
    peRatio: 25.5,
    pbRatio: 3.5,
    beta: 1.1,
    sharpe1y: 0.6,
    volatility1y: 22.0,
    returns1y: 8.5,
    returns3y: -3.5,
    returns5y: 3.2,
    topHoldings: JSON.stringify([
      { symbol: 'AMGN', name: 'Amgen Inc.', weight: 8.2 },
      { symbol: 'GILD', name: 'Gilead Sciences', weight: 6.5 },
      { symbol: 'REGN', name: 'Regeneron Pharma', weight: 5.8 },
      { symbol: 'MRNA', name: 'Moderna Inc.', weight: 4.5 },
      { symbol: 'VRTX', name: 'Vertex Pharma', weight: 4.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Biotechnology', weight: 85.0 },
      { sector: 'Pharmaceuticals', weight: 10.0 },
      { sector: 'Life Sciences', weight: 5.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 95.0 },
      { region: 'Other', weight: 5.0 },
    ]),
  },
  {
    symbol: 'XLE',
    name: 'Energy Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Energy Select Sector',
    aum: 30000,
    dividendYield: 3.5,
    peRatio: 11.5,
    pbRatio: 1.6,
    beta: 0.9,
    sharpe1y: 1.0,
    volatility1y: 20.0,
    returns1y: 8.0,
    returns3y: 12.5,
    returns5y: 5.5,
    topHoldings: JSON.stringify([
      { symbol: 'XOM', name: 'Exxon Mobil', weight: 22.5 },
      { symbol: 'CVX', name: 'Chevron Corp.', weight: 18.2 },
      { symbol: 'COP', name: 'ConocoPhillips', weight: 8.5 },
      { symbol: 'SLB', name: 'Schlumberger', weight: 5.8 },
      { symbol: 'EOG', name: 'EOG Resources', weight: 4.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Integrated Oil & Gas', weight: 42.0 },
      { sector: 'Oil & Gas Exploration', weight: 22.0 },
      { sector: 'Oil Equipment & Services', weight: 15.0 },
      { sector: 'Refining', weight: 10.0 },
      { sector: 'Other Energy', weight: 11.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 95.0 },
      { region: 'Other', weight: 5.0 },
    ]),
  },
  {
    symbol: 'XLY',
    name: 'Consumer Discretionary Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Consumer Discretionary Select Sector',
    aum: 18000,
    dividendYield: 0.9,
    peRatio: 28.5,
    pbRatio: 5.2,
    beta: 1.1,
    sharpe1y: 1.5,
    volatility1y: 16.0,
    returns1y: 20.0,
    returns3y: 6.5,
    returns5y: 12.0,
    topHoldings: JSON.stringify([
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 22.0 },
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 15.5 },
      { symbol: 'HD', name: 'Home Depot', weight: 8.2 },
      { symbol: 'MCD', name: "McDonald's Corp.", weight: 5.5 },
      { symbol: 'NKE', name: 'Nike Inc.', weight: 4.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Internet & Direct Marketing', weight: 28.0 },
      { sector: 'Auto & Components', weight: 18.0 },
      { sector: 'Retailing', weight: 22.0 },
      { sector: 'Hotels & Leisure', weight: 12.0 },
      { sector: 'Other Consumer Discretionary', weight: 20.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.0 },
      { region: 'Other', weight: 2.0 },
    ]),
  },
  {
    symbol: 'VNQ',
    name: 'Vanguard Real Estate ETF',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.12,
    trackingIndex: 'MSCI US Investable Market Real Estate 25/50',
    aum: 45000,
    dividendYield: 3.8,
    peRatio: 35.0,
    pbRatio: 2.0,
    beta: 0.85,
    sharpe1y: 0.8,
    volatility1y: 17.0,
    returns1y: 8.0,
    returns3y: -2.0,
    returns5y: 4.0,
    topHoldings: JSON.stringify([
      { symbol: 'PLD', name: 'Prologis Inc.', weight: 6.5 },
      { symbol: 'AMT', name: 'American Tower', weight: 5.8 },
      { symbol: 'CCI', name: 'Crown Castle', weight: 4.2 },
      { symbol: 'EQIX', name: 'Equinix Inc.', weight: 3.8 },
      { symbol: 'SPG', name: 'Simon Property Group', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Specialized REITs', weight: 35.0 },
      { sector: 'Industrial REITs', weight: 15.0 },
      { sector: 'Retail REITs', weight: 12.0 },
      { sector: 'Residential REITs', weight: 12.0 },
      { sector: 'Office REITs', weight: 8.0 },
      { sector: 'Healthcare REITs', weight: 8.0 },
      { sector: 'Other Real Estate', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 97.0 },
      { region: 'Other', weight: 3.0 },
    ]),
  },
  {
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    market: 'US',
    category: 'bond',
    expenseRatio: 0.15,
    trackingIndex: 'ICE BofA 20+ Year Treasury',
    aum: 52000,
    dividendYield: 4.0,
    peRatio: null,
    pbRatio: null,
    beta: -0.15,
    sharpe1y: 0.3,
    volatility1y: 14.5,
    returns1y: -2.0,
    returns3y: -12.0,
    returns5y: -3.0,
    topHoldings: JSON.stringify([
      { symbol: 'US30Y', name: 'US Treasury 30Y', weight: 55.0 },
      { symbol: 'US20Y', name: 'US Treasury 20Y', weight: 30.0 },
      { symbol: 'US25Y', name: 'US Treasury 25Y', weight: 15.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Government Bonds', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
];

/**
 * GET /api/etf/popular
 * Return a list of popular ETFs with their profiles.
 * Seeds the database with popular ETFs if none exist.
 */
export async function GET() {
  try {
    // 1. Check if any ETF profiles exist
    const existingCount = await db.eTFProfile.count();

    if (existingCount === 0) {
      // 2. Seed the database with popular ETFs
      await db.$transaction(
        POPULAR_ETFS.map((etf) =>
          db.eTFProfile.create({
            data: etf,
          })
        )
      );
    } else {
      // For existing DB, upsert any missing popular ETFs
      const existingSymbols = await db.eTFProfile.findMany({
        select: { symbol: true },
      });
      const symbolSet = new Set(existingSymbols.map((e) => e.symbol));

      const missing = POPULAR_ETFS.filter((etf) => !symbolSet.has(etf.symbol));
      if (missing.length > 0) {
        await db.$transaction(
          missing.map((etf) =>
            db.eTFProfile.create({
              data: etf,
            })
          )
        );
      }
    }

    // 3. Fetch and return all popular ETF profiles
    const popularSymbols = POPULAR_ETFS.map((e) => e.symbol);
    const profiles = await db.eTFProfile.findMany({
      where: { symbol: { in: popularSymbols } },
      orderBy: { aum: 'desc' },
    });

    // Parse JSON fields for the response
    const result = profiles.map((p) => ({
      ...p,
      topHoldings: p.topHoldings ? JSON.parse(p.topHoldings) : null,
      sectorWeights: p.sectorWeights ? JSON.parse(p.sectorWeights) : null,
      regionWeights: p.regionWeights ? JSON.parse(p.regionWeights) : null,
    }));

    return NextResponse.json(result);
  } catch (error) {
    console.error('Popular ETFs API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch popular ETFs' },
      { status: 500 }
    );
  }
}
