import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

/**
 * Predefined popular ETF data with well-known metrics.
 * Used to seed the database if no ETF profiles exist.
 */
const POPULAR_ETFS = [
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.09,
    trackingIndex: 'S&P 500',
    aum: 530000,
    dividendYield: 1.4,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 1.0,
    sharpe1y: 1.85,
    volatility1y: 12.5,
    returns1y: 24.5,
    returns3y: 10.2,
    returns5y: 15.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', weight: 3.3 },
      { symbol: 'GOOG', name: 'Alphabet Inc. Class C', weight: 3.1 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 2.1 },
      { symbol: 'LLY', name: 'Eli Lilly and Co.', weight: 1.8 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 1.7 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Industrials', weight: 8.2 },
      { sector: 'Consumer Staples', weight: 5.8 },
      { sector: 'Energy', weight: 3.8 },
      { sector: 'Utilities', weight: 2.5 },
      { sector: 'Real Estate', weight: 2.3 },
      { sector: 'Materials', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.5 },
      { region: 'Other', weight: 1.5 },
    ]),
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.20,
    trackingIndex: 'NASDAQ-100',
    aum: 260000,
    dividendYield: 0.6,
    peRatio: 32.1,
    pbRatio: 7.2,
    beta: 1.15,
    sharpe1y: 2.1,
    volatility1y: 18.2,
    returns1y: 28.3,
    returns3y: 12.5,
    returns5y: 19.1,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 8.5 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 8.2 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 7.5 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 5.2 },
      { symbol: 'META', name: 'Meta Platforms', weight: 4.8 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.', weight: 4.5 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 3.2 },
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 3.0 },
      { symbol: 'COST', name: 'Costco Wholesale', weight: 2.5 },
      { symbol: 'NFLX', name: 'Netflix Inc.', weight: 2.1 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 52.8 },
      { sector: 'Communication Services', weight: 16.2 },
      { sector: 'Consumer Discretionary', weight: 13.5 },
      { sector: 'Healthcare', weight: 7.5 },
      { sector: 'Industrials', weight: 5.2 },
      { sector: 'Consumer Staples', weight: 3.5 },
      { sector: 'Other', weight: 1.3 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 97.0 },
      { region: 'Other', weight: 3.0 },
    ]),
  },
  {
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.03,
    trackingIndex: 'CRSP US Total Market',
    aum: 340000,
    dividendYield: 1.3,
    peRatio: 24.0,
    pbRatio: 4.5,
    beta: 1.0,
    sharpe1y: 1.8,
    volatility1y: 13.0,
    returns1y: 23.0,
    returns3y: 9.5,
    returns5y: 14.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 6.2 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 5.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 4.5 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.2 },
      { symbol: 'META', name: 'Meta Platforms', weight: 2.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 28.5 },
      { sector: 'Healthcare', weight: 12.5 },
      { sector: 'Financials', weight: 12.0 },
      { sector: 'Consumer Discretionary', weight: 10.5 },
      { sector: 'Industrials', weight: 9.0 },
      { sector: 'Communication Services', weight: 7.5 },
      { sector: 'Consumer Staples', weight: 5.5 },
      { sector: 'Energy', weight: 4.0 },
      { sector: 'Utilities', weight: 2.8 },
      { sector: 'Real Estate', weight: 3.2 },
      { sector: 'Materials', weight: 2.5 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 99.0 },
      { region: 'Other', weight: 1.0 },
    ]),
  },
  {
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.03,
    trackingIndex: 'S&P 500',
    aum: 440000,
    dividendYield: 1.35,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 1.0,
    sharpe1y: 1.85,
    volatility1y: 12.5,
    returns1y: 24.5,
    returns3y: 10.2,
    returns5y: 15.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Industrials', weight: 8.2 },
      { sector: 'Consumer Staples', weight: 5.8 },
      { sector: 'Energy', weight: 3.8 },
      { sector: 'Utilities', weight: 2.5 },
      { sector: 'Real Estate', weight: 2.3 },
      { sector: 'Materials', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.5 },
      { region: 'Other', weight: 1.5 },
    ]),
  },
  {
    symbol: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.03,
    trackingIndex: 'S&P 500',
    aum: 420000,
    dividendYield: 1.35,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 1.0,
    sharpe1y: 1.85,
    volatility1y: 12.5,
    returns1y: 24.5,
    returns3y: 10.2,
    returns5y: 15.8,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Industrials', weight: 8.2 },
      { sector: 'Consumer Staples', weight: 5.8 },
      { sector: 'Energy', weight: 3.8 },
      { sector: 'Utilities', weight: 2.5 },
      { sector: 'Real Estate', weight: 2.3 },
      { sector: 'Materials', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.5 },
      { region: 'Other', weight: 1.5 },
    ]),
  },
  {
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    market: 'US',
    category: 'broad_market',
    expenseRatio: 0.19,
    trackingIndex: 'Russell 2000',
    aum: 64000,
    dividendYield: 1.2,
    peRatio: 18.5,
    pbRatio: 2.2,
    beta: 1.15,
    sharpe1y: 1.1,
    volatility1y: 19.5,
    returns1y: 15.0,
    returns3y: 3.5,
    returns5y: 8.2,
    topHoldings: JSON.stringify([
      { symbol: 'SMCI', name: 'Super Micro Computer', weight: 1.2 },
      { symbol: 'MSTR', name: 'MicroStrategy Inc.', weight: 1.0 },
      { symbol: 'INSM', name: 'Insmed Inc.', weight: 0.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Healthcare', weight: 18.5 },
      { sector: 'Industrials', weight: 17.0 },
      { sector: 'Financials', weight: 15.5 },
      { sector: 'Technology', weight: 14.2 },
      { sector: 'Consumer Discretionary', weight: 11.8 },
      { sector: 'Consumer Staples', weight: 5.5 },
      { sector: 'Real Estate', weight: 7.5 },
      { sector: 'Energy', weight: 4.8 },
      { sector: 'Materials', weight: 3.5 },
      { sector: 'Utilities', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 99.5 },
      { region: 'Other', weight: 0.5 },
    ]),
  },
  {
    symbol: 'EFA',
    name: 'iShares MSCI EAFE ETF',
    market: 'US',
    category: 'international',
    expenseRatio: 0.32,
    trackingIndex: 'MSCI EAFE',
    aum: 53000,
    dividendYield: 3.1,
    peRatio: 15.8,
    pbRatio: 1.8,
    beta: 0.85,
    sharpe1y: 1.2,
    volatility1y: 12.0,
    returns1y: 14.2,
    returns3y: 5.8,
    returns5y: 8.5,
    topHoldings: JSON.stringify([
      { symbol: 'NVO', name: 'Novo Nordisk', weight: 1.8 },
      { symbol: 'ASML', name: 'ASML Holding', weight: 1.5 },
      { symbol: 'SAP', name: 'SAP SE', weight: 1.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Financials', weight: 18.5 },
      { sector: 'Consumer Staples', weight: 12.0 },
      { sector: 'Healthcare', weight: 11.5 },
      { sector: 'Industrials', weight: 11.0 },
      { sector: 'Technology', weight: 10.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 7.5 },
      { sector: 'Materials', weight: 6.8 },
      { sector: 'Energy', weight: 5.2 },
      { sector: 'Utilities', weight: 3.8 },
      { sector: 'Real Estate', weight: 3.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'Japan', weight: 22.5 },
      { region: 'United Kingdom', weight: 15.2 },
      { region: 'France', weight: 10.8 },
      { region: 'Germany', weight: 8.5 },
      { region: 'Switzerland', weight: 8.2 },
      { region: 'Australia', weight: 6.8 },
      { region: 'Other', weight: 28.0 },
    ]),
  },
  {
    symbol: 'AGG',
    name: 'iShares Core US Aggregate Bond ETF',
    market: 'US',
    category: 'bond',
    expenseRatio: 0.03,
    trackingIndex: 'Bloomberg US Aggregate Bond',
    aum: 115000,
    dividendYield: 4.2,
    peRatio: null,
    pbRatio: null,
    beta: 0.05,
    sharpe1y: 0.5,
    volatility1y: 5.5,
    returns1y: 2.5,
    returns3y: -2.5,
    returns5y: 0.5,
    topHoldings: JSON.stringify([
      { symbol: 'US10Y', name: 'US Treasury 10Y', weight: 8.5 },
      { symbol: 'US5Y', name: 'US Treasury 5Y', weight: 6.2 },
      { symbol: 'US30Y', name: 'US Treasury 30Y', weight: 5.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Government', weight: 42.5 },
      { sector: 'Corporate (Investment Grade)', weight: 28.2 },
      { sector: 'Mortgage-Backed', weight: 25.0 },
      { sector: 'Other', weight: 4.3 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
  {
    symbol: 'BND',
    name: 'Vanguard Total Bond Market ETF',
    market: 'US',
    category: 'bond',
    expenseRatio: 0.03,
    trackingIndex: 'Bloomberg US Total Bond',
    aum: 100000,
    dividendYield: 4.1,
    peRatio: null,
    pbRatio: null,
    beta: 0.05,
    sharpe1y: 0.45,
    volatility1y: 5.8,
    returns1y: 2.2,
    returns3y: -2.8,
    returns5y: 0.3,
    topHoldings: JSON.stringify([
      { symbol: 'US10Y', name: 'US Treasury 10Y', weight: 9.0 },
      { symbol: 'US5Y', name: 'US Treasury 5Y', weight: 7.5 },
      { symbol: 'US30Y', name: 'US Treasury 30Y', weight: 5.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Government', weight: 45.0 },
      { sector: 'Corporate (Investment Grade)', weight: 25.5 },
      { sector: 'Mortgage-Backed', weight: 24.5 },
      { sector: 'Other', weight: 5.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
  {
    symbol: 'VWO',
    name: 'Vanguard Emerging Markets ETF',
    market: 'US',
    category: 'international',
    expenseRatio: 0.08,
    trackingIndex: 'FTSE Emerging Markets',
    aum: 78000,
    dividendYield: 2.8,
    peRatio: 14.2,
    pbRatio: 1.5,
    beta: 0.95,
    sharpe1y: 0.8,
    volatility1y: 15.5,
    returns1y: 10.5,
    returns3y: -2.5,
    returns5y: 3.2,
    topHoldings: JSON.stringify([
      { symbol: 'TSM', name: 'Taiwan Semiconductor', weight: 8.5 },
      { symbol: '600519.SS', name: 'Kweichow Moutai', weight: 2.2 },
      { symbol: 'PDD', name: 'PDD Holdings', weight: 1.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 22.5 },
      { sector: 'Financials', weight: 20.8 },
      { sector: 'Consumer Discretionary', weight: 12.5 },
      { sector: 'Communication Services', weight: 10.2 },
      { sector: 'Consumer Staples', weight: 7.5 },
      { sector: 'Materials', weight: 6.8 },
      { sector: 'Energy', weight: 5.5 },
      { sector: 'Industrials', weight: 5.0 },
      { sector: 'Healthcare', weight: 4.2 },
      { sector: 'Utilities', weight: 3.0 },
      { sector: 'Real Estate', weight: 2.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'China', weight: 32.5 },
      { region: 'Taiwan', weight: 18.2 },
      { region: 'India', weight: 14.5 },
      { region: 'Brazil', weight: 5.8 },
      { region: 'Saudi Arabia', weight: 4.2 },
      { region: 'South Africa', weight: 3.5 },
      { region: 'Other', weight: 21.3 },
    ]),
  },
  {
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    market: 'US',
    category: 'commodity',
    expenseRatio: 0.40,
    trackingIndex: 'Gold Price',
    aum: 72000,
    dividendYield: 0,
    peRatio: null,
    pbRatio: null,
    beta: -0.05,
    sharpe1y: 1.5,
    volatility1y: 13.0,
    returns1y: 20.0,
    returns3y: 8.5,
    returns5y: 10.5,
    topHoldings: JSON.stringify([
      { symbol: 'GOLD', name: 'Gold Bullion', weight: 99.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Commodities', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'Global', weight: 100.0 },
    ]),
  },
  {
    symbol: 'SLV',
    name: 'iShares Silver Trust',
    market: 'US',
    category: 'commodity',
    expenseRatio: 0.50,
    trackingIndex: 'Silver Price',
    aum: 15000,
    dividendYield: 0,
    peRatio: null,
    pbRatio: null,
    beta: 0.1,
    sharpe1y: 0.9,
    volatility1y: 22.0,
    returns1y: 18.0,
    returns3y: 5.2,
    returns5y: 7.8,
    topHoldings: JSON.stringify([
      { symbol: 'SILVER', name: 'Silver Bullion', weight: 99.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Commodities', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'Global', weight: 100.0 },
    ]),
  },
  {
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Financials Select Sector',
    aum: 42000,
    dividendYield: 1.6,
    peRatio: 14.5,
    pbRatio: 1.6,
    beta: 1.05,
    sharpe1y: 1.6,
    volatility1y: 15.0,
    returns1y: 18.5,
    returns3y: 8.2,
    returns5y: 10.5,
    topHoldings: JSON.stringify([
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 13.2 },
      { symbol: 'JPM', name: 'JPMorgan Chase', weight: 9.8 },
      { symbol: 'V', name: 'Visa Inc.', weight: 8.5 },
      { symbol: 'MA', name: 'Mastercard Inc.', weight: 7.2 },
      { symbol: 'BAC', name: 'Bank of America', weight: 5.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Banks', weight: 35.0 },
      { sector: 'Insurance', weight: 15.0 },
      { sector: 'Capital Markets', weight: 18.0 },
      { sector: 'Payment Processing', weight: 20.0 },
      { sector: 'Other Financials', weight: 12.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },
  {
    symbol: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Technology Select Sector',
    aum: 56000,
    dividendYield: 0.7,
    peRatio: 35.5,
    pbRatio: 8.5,
    beta: 1.2,
    sharpe1y: 2.2,
    volatility1y: 18.5,
    returns1y: 30.0,
    returns3y: 14.5,
    returns5y: 22.0,
    topHoldings: JSON.stringify([
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 21.5 },
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 20.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 12.5 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 5.2 },
      { symbol: 'CRM', name: 'Salesforce Inc.', weight: 3.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Software', weight: 35.0 },
      { sector: 'Semiconductors', weight: 25.0 },
      { sector: 'Hardware', weight: 18.0 },
      { sector: 'IT Services', weight: 12.0 },
      { sector: 'Other Technology', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.0 },
      { region: 'Other', weight: 2.0 },
    ]),
  },
  {
    symbol: 'VGT',
    name: 'Vanguard Information Technology ETF',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.10,
    trackingIndex: 'MSCI US Investable Market Info Tech 25/50',
    aum: 65000,
    dividendYield: 0.8,
    peRatio: 34.2,
    pbRatio: 9.0,
    beta: 1.18,
    sharpe1y: 2.15,
    volatility1y: 17.8,
    returns1y: 28.5,
    returns3y: 13.8,
    returns5y: 20.5,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 18.5 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 16.8 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 8.5 },
      { symbol: 'AVGO', name: 'Broadcom Inc.', weight: 4.2 },
      { symbol: 'CRM', name: 'Salesforce Inc.', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Software', weight: 38.0 },
      { sector: 'Semiconductors', weight: 22.0 },
      { sector: 'Hardware', weight: 15.0 },
      { sector: 'IT Services', weight: 14.0 },
      { sector: 'Other Technology', weight: 11.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 97.5 },
      { region: 'Other', weight: 2.5 },
    ]),
  },
  {
    symbol: 'IBB',
    name: 'iShares Biotechnology ETF',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.45,
    trackingIndex: 'ICE Biotechnology',
    aum: 8500,
    dividendYield: 0.3,
    peRatio: 25.5,
    pbRatio: 3.5,
    beta: 1.1,
    sharpe1y: 0.6,
    volatility1y: 22.0,
    returns1y: 8.5,
    returns3y: -3.5,
    returns5y: 3.2,
    topHoldings: JSON.stringify([
      { symbol: 'AMGN', name: 'Amgen Inc.', weight: 8.2 },
      { symbol: 'GILD', name: 'Gilead Sciences', weight: 6.5 },
      { symbol: 'REGN', name: 'Regeneron Pharma', weight: 5.8 },
      { symbol: 'MRNA', name: 'Moderna Inc.', weight: 4.5 },
      { symbol: 'VRTX', name: 'Vertex Pharma', weight: 4.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Biotechnology', weight: 85.0 },
      { sector: 'Pharmaceuticals', weight: 10.0 },
      { sector: 'Life Sciences', weight: 5.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 95.0 },
      { region: 'Other', weight: 5.0 },
    ]),
  },
  {
    symbol: 'XLE',
    name: 'Energy Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Energy Select Sector',
    aum: 30000,
    dividendYield: 3.5,
    peRatio: 11.5,
    pbRatio: 1.6,
    beta: 0.9,
    sharpe1y: 1.0,
    volatility1y: 20.0,
    returns1y: 8.0,
    returns3y: 12.5,
    returns5y: 5.5,
    topHoldings: JSON.stringify([
      { symbol: 'XOM', name: 'Exxon Mobil', weight: 22.5 },
      { symbol: 'CVX', name: 'Chevron Corp.', weight: 18.2 },
      { symbol: 'COP', name: 'ConocoPhillips', weight: 8.5 },
      { symbol: 'SLB', name: 'Schlumberger', weight: 5.8 },
      { symbol: 'EOG', name: 'EOG Resources', weight: 4.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Integrated Oil & Gas', weight: 42.0 },
      { sector: 'Oil & Gas Exploration', weight: 22.0 },
      { sector: 'Oil Equipment & Services', weight: 15.0 },
      { sector: 'Refining', weight: 10.0 },
      { sector: 'Other Energy', weight: 11.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 95.0 },
      { region: 'Other', weight: 5.0 },
    ]),
  },
  {
    symbol: 'XLY',
    name: 'Consumer Discretionary Select Sector SPDR Fund',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.08,
    trackingIndex: 'S&P Consumer Discretionary Select Sector',
    aum: 18000,
    dividendYield: 0.9,
    peRatio: 28.5,
    pbRatio: 5.2,
    beta: 1.1,
    sharpe1y: 1.5,
    volatility1y: 16.0,
    returns1y: 20.0,
    returns3y: 6.5,
    returns5y: 12.0,
    topHoldings: JSON.stringify([
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 22.0 },
      { symbol: 'TSLA', name: 'Tesla Inc.', weight: 15.5 },
      { symbol: 'HD', name: 'Home Depot', weight: 8.2 },
      { symbol: 'MCD', name: "McDonald's Corp.", weight: 5.5 },
      { symbol: 'NKE', name: 'Nike Inc.', weight: 4.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Internet & Direct Marketing', weight: 28.0 },
      { sector: 'Auto & Components', weight: 18.0 },
      { sector: 'Retailing', weight: 22.0 },
      { sector: 'Hotels & Leisure', weight: 12.0 },
      { sector: 'Other Consumer Discretionary', weight: 20.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 98.0 },
      { region: 'Other', weight: 2.0 },
    ]),
  },
  {
    symbol: 'VNQ',
    name: 'Vanguard Real Estate ETF',
    market: 'US',
    category: 'sector',
    expenseRatio: 0.12,
    trackingIndex: 'MSCI US Investable Market Real Estate 25/50',
    aum: 45000,
    dividendYield: 3.8,
    peRatio: 35.0,
    pbRatio: 2.0,
    beta: 0.85,
    sharpe1y: 0.8,
    volatility1y: 17.0,
    returns1y: 8.0,
    returns3y: -2.0,
    returns5y: 4.0,
    topHoldings: JSON.stringify([
      { symbol: 'PLD', name: 'Prologis Inc.', weight: 6.5 },
      { symbol: 'AMT', name: 'American Tower', weight: 5.8 },
      { symbol: 'CCI', name: 'Crown Castle', weight: 4.2 },
      { symbol: 'EQIX', name: 'Equinix Inc.', weight: 3.8 },
      { symbol: 'SPG', name: 'Simon Property Group', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Specialized REITs', weight: 35.0 },
      { sector: 'Industrial REITs', weight: 15.0 },
      { sector: 'Retail REITs', weight: 12.0 },
      { sector: 'Residential REITs', weight: 12.0 },
      { sector: 'Office REITs', weight: 8.0 },
      { sector: 'Healthcare REITs', weight: 8.0 },
      { sector: 'Other Real Estate', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 97.0 },
      { region: 'Other', weight: 3.0 },
    ]),
  },
  {
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    market: 'US',
    category: 'bond',
    expenseRatio: 0.15,
    trackingIndex: 'ICE BofA 20+ Year Treasury',
    aum: 52000,
    dividendYield: 4.0,
    peRatio: null,
    pbRatio: null,
    beta: -0.15,
    sharpe1y: 0.3,
    volatility1y: 14.5,
    returns1y: -2.0,
    returns3y: -12.0,
    returns5y: -3.0,
    topHoldings: JSON.stringify([
      { symbol: 'US30Y', name: 'US Treasury 30Y', weight: 55.0 },
      { symbol: 'US20Y', name: 'US Treasury 20Y', weight: 30.0 },
      { symbol: 'US25Y', name: 'US Treasury 25Y', weight: 15.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Government Bonds', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: 'United States', weight: 100.0 },
    ]),
  },

  // ===== Chinese A-Share ETFs =====
  // 宽基 (Broad Market)
  {
    symbol: '510050',
    name: '华夏上证50ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '上证50指数',
    aum: 8400,
    dividendYield: 2.8,
    peRatio: 10.2,
    pbRatio: 1.3,
    beta: 0.95,
    sharpe1y: 0.9,
    volatility1y: 18.5,
    returns1y: 12.5,
    returns3y: -3.2,
    returns5y: 3.8,
    topHoldings: JSON.stringify([
      { symbol: '600519', name: '贵州茅台', weight: 12.5 },
      { symbol: '601318', name: '中国平安', weight: 8.2 },
      { symbol: '600036', name: '招商银行', weight: 7.8 },
      { symbol: '601012', name: '隆基绿能', weight: 4.5 },
      { symbol: '600900', name: '长江电力', weight: 4.2 },
      { symbol: '601899', name: '紫金矿业', weight: 3.8 },
      { symbol: '600276', name: '恒瑞医药', weight: 3.5 },
      { symbol: '601166', name: '兴业银行', weight: 3.2 },
      { symbol: '600030', name: '中信证券', weight: 3.0 },
      { symbol: '601888', name: '中国中免', weight: 2.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '金融', weight: 28.5 },
      { sector: '消费', weight: 22.0 },
      { sector: '能源', weight: 10.5 },
      { sector: '医药', weight: 8.2 },
      { sector: '公用事业', weight: 7.5 },
      { sector: '科技', weight: 6.8 },
      { sector: '工业', weight: 5.5 },
      { sector: '材料', weight: 5.0 },
      { sector: '其他', weight: 6.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '510300',
    name: '华泰柏瑞沪深300ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '沪深300指数',
    aum: 10500,
    dividendYield: 2.5,
    peRatio: 11.8,
    pbRatio: 1.4,
    beta: 1.0,
    sharpe1y: 0.7,
    volatility1y: 17.8,
    returns1y: 8.5,
    returns3y: -5.5,
    returns5y: 2.5,
    topHoldings: JSON.stringify([
      { symbol: '600519', name: '贵州茅台', weight: 5.8 },
      { symbol: '601318', name: '中国平安', weight: 4.2 },
      { symbol: '600036', name: '招商银行', weight: 3.5 },
      { symbol: '300750', name: '宁德时代', weight: 3.2 },
      { symbol: '000858', name: '五粮液', weight: 2.8 },
      { symbol: '600900', name: '长江电力', weight: 2.5 },
      { symbol: '601899', name: '紫金矿业', weight: 2.2 },
      { symbol: '000333', name: '美的集团', weight: 2.0 },
      { symbol: '002594', name: '比亚迪', weight: 1.8 },
      { symbol: '600276', name: '恒瑞医药', weight: 1.6 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '金融', weight: 22.5 },
      { sector: '消费', weight: 18.0 },
      { sector: '科技', weight: 12.5 },
      { sector: '工业', weight: 11.0 },
      { sector: '医药', weight: 8.5 },
      { sector: '能源', weight: 7.2 },
      { sector: '材料', weight: 6.8 },
      { sector: '公用事业', weight: 5.0 },
      { sector: '房地产', weight: 3.5 },
      { sector: '其他', weight: 5.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '510500',
    name: '华夏中证500ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '中证500指数',
    aum: 4200,
    dividendYield: 1.8,
    peRatio: 22.5,
    pbRatio: 1.8,
    beta: 1.05,
    sharpe1y: 0.3,
    volatility1y: 21.0,
    returns1y: -2.5,
    returns3y: -8.2,
    returns5y: 1.5,
    topHoldings: JSON.stringify([
      { symbol: '002460', name: '赣锋锂业', weight: 1.2 },
      { symbol: '601012', name: '隆基绿能', weight: 1.0 },
      { symbol: '002475', name: '立讯精密', weight: 0.9 },
      { symbol: '600809', name: '山西汾酒', weight: 0.8 },
      { symbol: '002371', name: '北方华创', weight: 0.7 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '工业', weight: 22.0 },
      { sector: '材料', weight: 18.5 },
      { sector: '科技', weight: 15.2 },
      { sector: '消费', weight: 12.8 },
      { sector: '医药', weight: 10.5 },
      { sector: '金融', weight: 5.0 },
      { sector: '能源', weight: 8.0 },
      { sector: '其他', weight: 8.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '159919',
    name: '嘉实沪深300ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '沪深300指数',
    aum: 2800,
    dividendYield: 2.5,
    peRatio: 11.8,
    pbRatio: 1.4,
    beta: 1.0,
    sharpe1y: 0.7,
    volatility1y: 17.8,
    returns1y: 8.5,
    returns3y: -5.5,
    returns5y: 2.5,
    topHoldings: JSON.stringify([
      { symbol: '600519', name: '贵州茅台', weight: 5.8 },
      { symbol: '601318', name: '中国平安', weight: 4.2 },
      { symbol: '600036', name: '招商银行', weight: 3.5 },
      { symbol: '300750', name: '宁德时代', weight: 3.2 },
      { symbol: '000858', name: '五粮液', weight: 2.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '金融', weight: 22.5 },
      { sector: '消费', weight: 18.0 },
      { sector: '科技', weight: 12.5 },
      { sector: '工业', weight: 11.0 },
      { sector: '医药', weight: 8.5 },
      { sector: '能源', weight: 7.2 },
      { sector: '材料', weight: 6.8 },
      { sector: '其他', weight: 13.5 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '512100',
    name: '南方中证1000ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '中证1000指数',
    aum: 1800,
    dividendYield: 1.2,
    peRatio: 28.5,
    pbRatio: 2.2,
    beta: 1.12,
    sharpe1y: -0.2,
    volatility1y: 24.5,
    returns1y: -8.5,
    returns3y: -12.0,
    returns5y: -1.0,
    topHoldings: JSON.stringify([
      { symbol: '002460', name: '赣锋锂业', weight: 0.6 },
      { symbol: '300124', name: '汇川技术', weight: 0.5 },
      { symbol: '002371', name: '北方华创', weight: 0.5 },
      { symbol: '603501', name: '韦尔股份', weight: 0.4 },
      { symbol: '002049', name: '紫光国微', weight: 0.4 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '科技', weight: 22.0 },
      { sector: '工业', weight: 20.5 },
      { sector: '材料', weight: 15.8 },
      { sector: '医药', weight: 12.2 },
      { sector: '消费', weight: 10.5 },
      { sector: '能源', weight: 8.0 },
      { sector: '其他', weight: 11.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '588000',
    name: '华夏科创50ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '科创50指数',
    aum: 3500,
    dividendYield: 0.8,
    peRatio: 45.2,
    pbRatio: 4.5,
    beta: 1.25,
    sharpe1y: -0.5,
    volatility1y: 28.5,
    returns1y: -15.0,
    returns3y: -18.5,
    returns5y: -5.0,
    topHoldings: JSON.stringify([
      { symbol: '688981', name: '中芯国际', weight: 8.5 },
      { symbol: '688012', name: '中微公司', weight: 5.2 },
      { symbol: '688256', name: '寒武纪', weight: 4.8 },
      { symbol: '688111', name: '金山办公', weight: 4.5 },
      { symbol: '688036', name: '传音控股', weight: 3.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '半导体', weight: 35.0 },
      { sector: '软件', weight: 18.5 },
      { sector: '生物医药', weight: 15.2 },
      { sector: '新能源', weight: 12.8 },
      { sector: '高端装备', weight: 10.0 },
      { sector: '其他', weight: 8.5 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '159915',
    name: '易方达创业板ETF',
    market: 'A',
    category: 'broad_market',
    expenseRatio: 0.50,
    trackingIndex: '创业板指数',
    aum: 2200,
    dividendYield: 0.5,
    peRatio: 35.8,
    pbRatio: 4.2,
    beta: 1.2,
    sharpe1y: -0.4,
    volatility1y: 26.0,
    returns1y: -12.0,
    returns3y: -15.0,
    returns5y: 5.0,
    topHoldings: JSON.stringify([
      { symbol: '300750', name: '宁德时代', weight: 15.5 },
      { symbol: '300059', name: '东方财富', weight: 5.2 },
      { symbol: '300760', name: '迈瑞医疗', weight: 4.8 },
      { symbol: '300124', name: '汇川技术', weight: 3.5 },
      { symbol: '300015', name: '爱尔眼科', weight: 3.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '新能源', weight: 25.0 },
      { sector: '科技', weight: 20.5 },
      { sector: '医药', weight: 15.8 },
      { sector: '金融', weight: 12.0 },
      { sector: '工业', weight: 10.2 },
      { sector: '消费', weight: 8.5 },
      { sector: '其他', weight: 8.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },

  // 跨境 (Cross-border / International)
  {
    symbol: '513500',
    name: '博时标普500ETF',
    market: 'A',
    category: 'international',
    expenseRatio: 0.60,
    trackingIndex: 'S&P 500',
    aum: 700,
    dividendYield: 1.2,
    peRatio: 23.5,
    pbRatio: 4.8,
    beta: 0.85,
    sharpe1y: 1.8,
    volatility1y: 14.5,
    returns1y: 22.0,
    returns3y: 8.5,
    returns5y: 14.0,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 7.1 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 6.5 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 5.8 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 3.8 },
      { symbol: 'META', name: 'Meta Platforms', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 31.5 },
      { sector: 'Healthcare', weight: 11.8 },
      { sector: 'Financials', weight: 11.5 },
      { sector: 'Consumer Discretionary', weight: 10.2 },
      { sector: 'Communication Services', weight: 8.5 },
      { sector: 'Other', weight: 26.5 },
    ]),
    regionWeights: JSON.stringify([
      { region: '美国', weight: 98.5 },
      { region: '其他', weight: 1.5 },
    ]),
  },
  {
    symbol: '513300',
    name: '华夏沪深300ETF',
    market: 'A',
    category: 'international',
    expenseRatio: 0.50,
    trackingIndex: '沪深300指数',
    aum: 450,
    dividendYield: 2.2,
    peRatio: 12.5,
    pbRatio: 1.4,
    beta: 0.92,
    sharpe1y: 0.6,
    volatility1y: 18.0,
    returns1y: 5.0,
    returns3y: -8.0,
    returns5y: 2.0,
    topHoldings: JSON.stringify([
      { symbol: '600519', name: '贵州茅台', weight: 6.5 },
      { symbol: '601318', name: '中国平安', weight: 4.2 },
      { symbol: '600036', name: '招商银行', weight: 3.8 },
      { symbol: '000858', name: '五粮液', weight: 2.8 },
      { symbol: '601012', name: '隆基绿能', weight: 2.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '金融', weight: 22.5 },
      { sector: '消费', weight: 18.0 },
      { sector: '科技', weight: 15.0 },
      { sector: '工业', weight: 12.0 },
      { sector: '医药', weight: 8.5 },
      { sector: '其他', weight: 24.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '513100',
    name: '国泰纳斯达克100ETF',
    market: 'A',
    category: 'international',
    expenseRatio: 0.80,
    trackingIndex: 'NASDAQ-100',
    aum: 560,
    dividendYield: 0.5,
    peRatio: 32.1,
    pbRatio: 7.2,
    beta: 0.95,
    sharpe1y: 2.0,
    volatility1y: 19.5,
    returns1y: 25.0,
    returns3y: 10.0,
    returns5y: 17.0,
    topHoldings: JSON.stringify([
      { symbol: 'AAPL', name: 'Apple Inc.', weight: 8.5 },
      { symbol: 'MSFT', name: 'Microsoft Corp.', weight: 8.2 },
      { symbol: 'NVDA', name: 'NVIDIA Corp.', weight: 7.5 },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', weight: 5.2 },
      { symbol: 'META', name: 'Meta Platforms', weight: 4.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: 'Technology', weight: 52.8 },
      { sector: 'Communication Services', weight: 16.2 },
      { sector: 'Consumer Discretionary', weight: 13.5 },
      { sector: 'Healthcare', weight: 7.5 },
      { sector: 'Other', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '美国', weight: 97.0 },
      { region: '其他', weight: 3.0 },
    ]),
  },
  {
    symbol: '513030',
    name: '华安德国DAX ETF',
    market: 'A',
    category: 'international',
    expenseRatio: 0.80,
    trackingIndex: 'DAX指数',
    aum: 42,
    dividendYield: 2.5,
    peRatio: 14.5,
    pbRatio: 1.6,
    beta: 0.75,
    sharpe1y: 0.8,
    volatility1y: 15.0,
    returns1y: 10.5,
    returns3y: 2.0,
    returns5y: 5.0,
    topHoldings: JSON.stringify([
      { symbol: 'SAP', name: 'SAP SE', weight: 10.5 },
      { symbol: 'SIE', name: 'Siemens AG', weight: 8.2 },
      { symbol: 'ALV', name: 'Allianz SE', weight: 7.5 },
      { symbol: 'DTE', name: 'Deutsche Telekom', weight: 6.8 },
      { symbol: 'AIR', name: 'Airbus SE', weight: 5.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '工业', weight: 22.0 },
      { sector: '金融', weight: 18.5 },
      { sector: '科技', weight: 15.2 },
      { sector: '消费', weight: 12.8 },
      { sector: '医疗', weight: 10.5 },
      { sector: '其他', weight: 21.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '德国', weight: 95.0 },
      { region: '其他', weight: 5.0 },
    ]),
  },
  {
    symbol: '513060',
    name: '华夏恒生ETF',
    market: 'A',
    category: 'international',
    expenseRatio: 0.60,
    trackingIndex: '恒生指数',
    aum: 580,
    dividendYield: 3.5,
    peRatio: 9.5,
    pbRatio: 1.0,
    beta: 0.9,
    sharpe1y: -0.2,
    volatility1y: 22.0,
    returns1y: -5.0,
    returns3y: -12.5,
    returns5y: -5.0,
    topHoldings: JSON.stringify([
      { symbol: '0941', name: '中国移动', weight: 8.2 },
      { symbol: '9988', name: '阿里巴巴', weight: 7.5 },
      { symbol: '9999', name: '网易', weight: 5.8 },
      { symbol: '0883', name: '中海油', weight: 5.2 },
      { symbol: '1299', name: '友邦保险', weight: 4.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '金融', weight: 30.5 },
      { sector: '科技', weight: 22.0 },
      { sector: '消费', weight: 12.5 },
      { sector: '能源', weight: 8.2 },
      { sector: '公用事业', weight: 7.5 },
      { sector: '其他', weight: 19.3 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国香港', weight: 65.0 },
      { region: '中国大陆', weight: 30.0 },
      { region: '其他', weight: 5.0 },
    ]),
  },
  {
    symbol: '513080',
    name: '易方达日兴资管日经225ETF',
    market: 'A',
    category: 'international',
    expenseRatio: 0.90,
    trackingIndex: '日经225',
    aum: 35,
    dividendYield: 1.8,
    peRatio: 16.5,
    pbRatio: 1.8,
    beta: 0.7,
    sharpe1y: 1.2,
    volatility1y: 16.0,
    returns1y: 18.0,
    returns3y: 8.0,
    returns5y: 10.0,
    topHoldings: JSON.stringify([
      { symbol: '7203', name: 'Toyota Motor', weight: 4.5 },
      { symbol: '6758', name: 'Sony Group', weight: 3.2 },
      { symbol: '9984', name: 'SoftBank Group', weight: 2.8 },
      { symbol: '6861', name: 'Keyence Corp.', weight: 2.5 },
      { symbol: '7974', name: 'Nintendo', weight: 2.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '工业', weight: 25.0 },
      { sector: '科技', weight: 20.0 },
      { sector: '消费', weight: 18.5 },
      { sector: '金融', weight: 12.5 },
      { sector: '医疗', weight: 8.0 },
      { sector: '其他', weight: 16.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '日本', weight: 100.0 },
    ]),
  },

  // 行业 (Sector)
  {
    symbol: '512480',
    name: '国联安半导体ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.95,
    trackingIndex: '中证全指半导体',
    aum: 2100,
    dividendYield: 0.2,
    peRatio: 55.0,
    pbRatio: 5.5,
    beta: 1.45,
    sharpe1y: -0.3,
    volatility1y: 32.0,
    returns1y: -10.0,
    returns3y: -8.0,
    returns5y: 15.0,
    topHoldings: JSON.stringify([
      { symbol: '002049', name: '紫光国微', weight: 8.5 },
      { symbol: '603501', name: '韦尔股份', weight: 7.2 },
      { symbol: '688981', name: '中芯国际', weight: 6.8 },
      { symbol: '688012', name: '中微公司', weight: 5.5 },
      { symbol: '300782', name: '卓胜微', weight: 4.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '芯片设计', weight: 35.0 },
      { sector: '晶圆制造', weight: 25.0 },
      { sector: '半导体设备', weight: 18.0 },
      { sector: '封装测试', weight: 12.0 },
      { sector: '半导体材料', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '512660',
    name: '国泰军工ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.60,
    trackingIndex: '中证军工指数',
    aum: 1800,
    dividendYield: 0.5,
    peRatio: 52.0,
    pbRatio: 3.5,
    beta: 1.15,
    sharpe1y: -0.5,
    volatility1y: 25.0,
    returns1y: -12.0,
    returns3y: -10.0,
    returns5y: 8.0,
    topHoldings: JSON.stringify([
      { symbol: '600760', name: '中航沈飞', weight: 5.2 },
      { symbol: '600893', name: '航发动力', weight: 4.8 },
      { symbol: '002179', name: '中航光电', weight: 4.5 },
      { symbol: '600862', name: '中航高科', weight: 3.8 },
      { symbol: '600038', name: '中直股份', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '航空装备', weight: 30.0 },
      { sector: '航天装备', weight: 18.0 },
      { sector: '军工电子', weight: 22.0 },
      { sector: '兵器装备', weight: 12.0 },
      { sector: '舰船装备', weight: 10.0 },
      { sector: '其他', weight: 8.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '512170',
    name: '华宝医疗ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证医疗指数',
    aum: 1200,
    dividendYield: 0.8,
    peRatio: 28.5,
    pbRatio: 3.8,
    beta: 1.05,
    sharpe1y: -0.8,
    volatility1y: 24.0,
    returns1y: -18.0,
    returns3y: -22.0,
    returns5y: -8.0,
    topHoldings: JSON.stringify([
      { symbol: '300760', name: '迈瑞医疗', weight: 10.5 },
      { symbol: '300015', name: '爱尔眼科', weight: 6.8 },
      { symbol: '603259', name: '药明康德', weight: 5.5 },
      { symbol: '300122', name: '智飞生物', weight: 4.2 },
      { symbol: '300347', name: '泰格医药', weight: 3.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '医疗器械', weight: 25.0 },
      { sector: 'CXO', weight: 20.0 },
      { sector: '疫苗', weight: 15.0 },
      { sector: '医疗服务', weight: 18.0 },
      { sector: '体外诊断', weight: 12.0 },
      { sector: '其他', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '512800',
    name: '南方银行ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证银行指数',
    aum: 950,
    dividendYield: 5.2,
    peRatio: 5.8,
    pbRatio: 0.6,
    beta: 0.75,
    sharpe1y: 1.2,
    volatility1y: 12.0,
    returns1y: 15.0,
    returns3y: 2.0,
    returns5y: 3.5,
    topHoldings: JSON.stringify([
      { symbol: '600036', name: '招商银行', weight: 12.5 },
      { symbol: '601166', name: '兴业银行', weight: 8.8 },
      { symbol: '601398', name: '工商银行', weight: 7.5 },
      { symbol: '600016', name: '民生银行', weight: 5.2 },
      { symbol: '601288', name: '农业银行', weight: 4.8 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '股份制银行', weight: 38.0 },
      { sector: '国有大行', weight: 28.0 },
      { sector: '城商行', weight: 18.0 },
      { sector: '农商行', weight: 8.0 },
      { sector: '其他', weight: 8.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '515030',
    name: '华夏新能源车ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证新能源车指数',
    aum: 1500,
    dividendYield: 0.3,
    peRatio: 30.5,
    pbRatio: 3.2,
    beta: 1.3,
    sharpe1y: -0.6,
    volatility1y: 28.0,
    returns1y: -15.0,
    returns3y: -5.0,
    returns5y: 12.0,
    topHoldings: JSON.stringify([
      { symbol: '300750', name: '宁德时代', weight: 12.0 },
      { symbol: '002594', name: '比亚迪', weight: 8.5 },
      { symbol: '600104', name: '上汽集团', weight: 3.8 },
      { symbol: '002460', name: '赣锋锂业', weight: 3.5 },
      { symbol: '300014', name: '亿纬锂能', weight: 3.2 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '锂电池', weight: 28.0 },
      { sector: '整车', weight: 22.0 },
      { sector: '汽车零部件', weight: 18.0 },
      { sector: '充电桩', weight: 12.0 },
      { sector: '资源', weight: 10.0 },
      { sector: '其他', weight: 10.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '515790',
    name: '华泰柏瑞光伏ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证光伏产业指数',
    aum: 800,
    dividendYield: 0.5,
    peRatio: 18.0,
    pbRatio: 2.5,
    beta: 1.35,
    sharpe1y: -1.0,
    volatility1y: 30.0,
    returns1y: -22.0,
    returns3y: -15.0,
    returns5y: 5.0,
    topHoldings: JSON.stringify([
      { symbol: '601012', name: '隆基绿能', weight: 10.5 },
      { symbol: '002459', name: '晶澳科技', weight: 7.2 },
      { symbol: '600438', name: '通威股份', weight: 6.8 },
      { symbol: '601865', name: '福莱特', weight: 4.5 },
      { symbol: '002129', name: '中环股份', weight: 4.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '硅片', weight: 22.0 },
      { sector: '电池片', weight: 18.0 },
      { sector: '组件', weight: 20.0 },
      { sector: '辅材', weight: 15.0 },
      { sector: '逆变器', weight: 12.0 },
      { sector: '其他', weight: 13.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '159869',
    name: '华夏游戏ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证动漫游戏指数',
    aum: 280,
    dividendYield: 1.0,
    peRatio: 25.0,
    pbRatio: 3.0,
    beta: 1.1,
    sharpe1y: 0.5,
    volatility1y: 26.0,
    returns1y: 10.0,
    returns3y: -5.0,
    returns5y: 8.0,
    topHoldings: JSON.stringify([
      { symbol: '002602', name: '世纪华通', weight: 8.5 },
      { symbol: '300418', name: '昆仑万维', weight: 7.2 },
      { symbol: '601919', name: '完美世界', weight: 6.0 },
      { symbol: '002555', name: '三七互娱', weight: 5.8 },
      { symbol: '300315', name: '掌趣科技', weight: 4.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '游戏开发', weight: 45.0 },
      { sector: '游戏运营', weight: 25.0 },
      { sector: '动漫', weight: 15.0 },
      { sector: '其他', weight: 15.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '512200',
    name: '南方房地产ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证房地产指数',
    aum: 150,
    dividendYield: 4.0,
    peRatio: 12.0,
    pbRatio: 0.8,
    beta: 1.05,
    sharpe1y: -1.5,
    volatility1y: 28.0,
    returns1y: -25.0,
    returns3y: -30.0,
    returns5y: -15.0,
    topHoldings: JSON.stringify([
      { symbol: '001979', name: '招商蛇口', weight: 8.5 },
      { symbol: '600048', name: '保利发展', weight: 7.8 },
      { symbol: '000002', name: '万科A', weight: 6.5 },
      { symbol: '601155', name: '新城控股', weight: 4.2 },
      { symbol: '001914', name: '招商积余', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '住宅开发', weight: 55.0 },
      { sector: '园区开发', weight: 15.0 },
      { sector: '物业管理', weight: 12.0 },
      { sector: '商业地产', weight: 10.0 },
      { sector: '其他', weight: 8.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '515050',
    name: '华夏5GETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证5G通信主题指数',
    aum: 680,
    dividendYield: 0.8,
    peRatio: 28.0,
    pbRatio: 3.0,
    beta: 1.15,
    sharpe1y: -0.3,
    volatility1y: 25.0,
    returns1y: -8.0,
    returns3y: -10.0,
    returns5y: 5.0,
    topHoldings: JSON.stringify([
      { symbol: '000063', name: '中兴通讯', weight: 8.5 },
      { symbol: '002475', name: '立讯精密', weight: 7.2 },
      { symbol: '600487', name: '亨通光电', weight: 4.5 },
      { symbol: '002236', name: '大华股份', weight: 3.8 },
      { symbol: '600050', name: '中国联通', weight: 3.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '通信设备', weight: 35.0 },
      { sector: '通信运营', weight: 18.0 },
      { sector: '电子元件', weight: 22.0 },
      { sector: '计算机', weight: 12.0 },
      { sector: '其他', weight: 13.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '512010',
    name: '国泰医药ETF',
    market: 'A',
    category: 'sector',
    expenseRatio: 0.50,
    trackingIndex: '中证医药卫生指数',
    aum: 1100,
    dividendYield: 1.2,
    peRatio: 25.5,
    pbRatio: 3.5,
    beta: 0.95,
    sharpe1y: -0.6,
    volatility1y: 20.0,
    returns1y: -12.0,
    returns3y: -15.0,
    returns5y: 0.0,
    topHoldings: JSON.stringify([
      { symbol: '600276', name: '恒瑞医药', weight: 8.2 },
      { symbol: '300760', name: '迈瑞医疗', weight: 6.5 },
      { symbol: '000538', name: '云南白药', weight: 4.0 },
      { symbol: '600085', name: '同仁堂', weight: 3.5 },
      { symbol: '002007', name: '华兰生物', weight: 3.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '化学制药', weight: 25.0 },
      { sector: '中药', weight: 18.0 },
      { sector: '医疗器械', weight: 15.0 },
      { sector: '生物制品', weight: 15.0 },
      { sector: '医药商业', weight: 12.0 },
      { sector: '医疗服务', weight: 10.0 },
      { sector: '其他', weight: 5.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },

  // 债券 (Bond)
  {
    symbol: '511010',
    name: '国泰上证5年期国债ETF',
    market: 'A',
    category: 'bond',
    expenseRatio: 0.30,
    trackingIndex: '上证5年期国债指数',
    aum: 350,
    dividendYield: 2.5,
    peRatio: null,
    pbRatio: null,
    beta: 0.02,
    sharpe1y: 0.8,
    volatility1y: 2.0,
    returns1y: 3.2,
    returns3y: 2.8,
    returns5y: 3.0,
    topHoldings: JSON.stringify([
      { symbol: 'T5Y001', name: '5年期国债230015', weight: 15.0 },
      { symbol: 'T5Y002', name: '5年期国债230018', weight: 12.5 },
      { symbol: 'T5Y003', name: '5年期国债240001', weight: 10.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '国债', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },
  {
    symbol: '511260',
    name: '国泰上证10年期国债ETF',
    market: 'A',
    category: 'bond',
    expenseRatio: 0.30,
    trackingIndex: '上证10年期国债指数',
    aum: 280,
    dividendYield: 2.8,
    peRatio: null,
    pbRatio: null,
    beta: -0.05,
    sharpe1y: 0.5,
    volatility1y: 3.5,
    returns1y: 2.5,
    returns3y: 2.0,
    returns5y: 2.8,
    topHoldings: JSON.stringify([
      { symbol: 'T10Y001', name: '10年期国债230019', weight: 18.0 },
      { symbol: 'T10Y002', name: '10年期国债240004', weight: 15.0 },
      { symbol: 'T10Y003', name: '10年期国债230005', weight: 12.0 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '国债', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '中国大陆', weight: 100.0 },
    ]),
  },

  // 商品 (Commodity)
  {
    symbol: '518880',
    name: '华安黄金ETF',
    market: 'A',
    category: 'commodity',
    expenseRatio: 0.50,
    trackingIndex: '黄金现货',
    aum: 2100,
    dividendYield: 0,
    peRatio: null,
    pbRatio: null,
    beta: -0.05,
    sharpe1y: 1.8,
    volatility1y: 14.0,
    returns1y: 25.0,
    returns3y: 12.0,
    returns5y: 10.0,
    topHoldings: JSON.stringify([
      { symbol: 'AU9999', name: '黄金现货', weight: 99.5 },
    ]),
    sectorWeights: JSON.stringify([
      { sector: '贵金属', weight: 100.0 },
    ]),
    regionWeights: JSON.stringify([
      { region: '全球', weight: 100.0 },
    ]),
  },
];

/**
 * GET /api/etf/popular
 * Return a list of popular ETFs with their profiles.
 * Seeds the database with popular ETFs if none exist.
 */
export async function GET() {
  try {
    // 1. Check if any ETF profiles exist
    const existingCount = await db.eTFProfile.count();

    if (existingCount === 0) {
      // 2. Seed the database with popular ETFs
      await db.$transaction(
        POPULAR_ETFS.map((etf) =>
          db.eTFProfile.create({
            data: etf,
          })
        )
      );
    } else {
      // For existing DB, upsert any missing popular ETFs
      const existingSymbols = await db.eTFProfile.findMany({
        select: { symbol: true },
      });
      const symbolSet = new Set(existingSymbols.map((e) => e.symbol));

      const missing = POPULAR_ETFS.filter((etf) => !symbolSet.has(etf.symbol));
      if (missing.length > 0) {
        await db.$transaction(
          missing.map((etf) =>
            db.eTFProfile.create({
              data: etf,
            })
          )
        );
      }
    }

    // 3. Fetch and return all popular ETF profiles
    const popularSymbols = POPULAR_ETFS.map((e) => e.symbol);
    const profiles = await db.eTFProfile.findMany({
      where: { symbol: { in: popularSymbols } },
      orderBy: { aum: 'desc' },
    });

    // Parse JSON fields for the response
    const result = profiles.map((p) => ({
      ...p,
      topHoldings: p.topHoldings ? JSON.parse(p.topHoldings) : null,
      sectorWeights: p.sectorWeights ? JSON.parse(p.sectorWeights) : null,
      regionWeights: p.regionWeights ? JSON.parse(p.regionWeights) : null,
    }));

    return NextResponse.json(result);
  } catch (error) {
    console.error('Popular ETFs API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch popular ETFs' },
      { status: 500 }
    );
  }
}
